
INSERT INTO CONTATOS (ID_LOGIN, NOME,NUMERO_PRINCIPAL) VALUES(3, 'ROGER', '112897-0987');
SELECT * FROM CONTATOS;
SELECT * FROM HISTORICO_CONTATOS;

DELETE FROM CONTATOS WHERE ID_CONTATO = (SELECT MAX(ID_CONTATO) FROM CONTATOS);
SELECT * FROM CONTATOS;
SELECT * FROM HISTORICO_CONTATOS;
