CREATE DATABASE BD_AGENDA;
USE BD_AGENDA;

CREATE TABLE LOGIN(
ID_LOGIN INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(250) NOT NULL,
NICKNAME VARCHAR(20) UNIQUE NOT NULL,
SENHA VARCHAR(30) NOT NULL,
PERGUNTA VARCHAR(800) NOT NULL,
RESPOSTA VARCHAR(800) NOT NULL,
LOGIN_ATIVO CHAR DEFAULT 'Y',
CONSTRAINT CK_NICKNAME CHECK(LENGTH(NICKNAME) >= 3),
CONSTRAINT CK_SENHA CHECK(LENGTH(SENHA) > 3),
DATA_CRIACAO DATETIME DEFAULT NOW(),
DATA_ALTERACAO DATETIME DEFAULT NOW()
);

CREATE TABLE CONTATOS(
ID_CONTATO INT PRIMARY KEY AUTO_INCREMENT,
ID_LOGIN INT NOT NULL,
NOME VARCHAR(250) NOT NULL,
NUMERO_PRINCIPAL VARCHAR(15) NOT NULL,
NUMERO_SECUNDARIO VARCHAR(15),
DATA_CRIACAO DATETIME DEFAULT NOW(),
DATA_ALTERACAO DATETIME DEFAULT NOW(),
CONSTRAINT FK_ID_LOGIN FOREIGN KEY(ID_LOGIN) REFERENCES LOGIN(ID_LOGIN)
);

CREATE TABLE HISTORICO_CONTATOS(
ID_HISTORICO INT PRIMARY KEY AUTO_INCREMENT,
ID_LOGIN INT NOT NULL,
ID_CONTATO INT NOT NULL,
NOME VARCHAR(250) NOT NULL,
NUMERO_PRINCIPAL VARCHAR(15) NOT NULL,
NUMERO_SECUNDARIO VARCHAR(15),
STATUS_CONTATO VARCHAR(20) DEFAULT 'ATIVO',
DATA_CRIACAO DATETIME DEFAULT NOW(),
DATA_ALTERACAO DATETIME DEFAULT NOW(),
CONSTRAINT CK_STATUS_CONTATO CHECK(STATUS_CONTATO IN('ATIVO','EXCLUIDO'))
);

CREATE OR REPLACE VIEW CONTATOS__DESC_V AS
SELECT C.ID_LOGIN,
       C.NOME,
       C.NUMERO_PRINCIPAL,
       CASE
        WHEN C.NUMERO_SECUNDARIO IS NULL OR UPPER(C.NUMERO_SECUNDARIO) IN('NULL', 'NONE')
             OR C.NUMERO_SECUNDARIO = "" THEN
             'Não possuí um 2º Número'
		ELSE
          C.NUMERO_SECUNDARIO 
	  END NUMERO_SECUNDARIO
FROM CONTATOS C
ORDER BY C.NOME;

CREATE OR REPLACE VIEW HISTORICO_CONTATOS_DESC_V AS
SELECT HC.NOME
      ,HC.NUMERO_PRINCIPAL
      , CASE 
        WHEN HC.NUMERO_SECUNDARIO IS NULL OR UPPER(HC.NUMERO_SECUNDARIO) IN('NULL','NONE') OR 
             HC.NUMERO_SECUNDARIO = "" THEN
	      'Não tem Número Secundário.'
		ELSE
          HC.NUMERO_SECUNDARIO
        END NUMERO_SECUNDARIO
      ,HC.STATUS_CONTATO
      ,DATE_FORMAT(HC.DATA_CRIACAO,'%d/%m/%Y %H:%i:%s') DATA_CRIACAO
      ,DATE_FORMAT(HC.DATA_ALTERACAO,'%d/%m/%Y %H:%i:%s')DATA_ALTERACAO
      ,HC.ID_LOGIN
 FROM HISTORICO_CONTATOS HC 
 ORDER BY HC.DATA_ALTERACAO DESC;
 
 
 
 

 
 
 