USE BD_AGENDA;

DROP TRIGGER ALTERAR_REG_HISTORIO_CONTATOS_BU;
DELIMITER $$;
CREATE TRIGGER ALTERAR_REG_HISTORIO_CONTATOS_BU BEFORE
UPDATE ON CONTATOS FOR EACH ROW

BEGIN
  DECLARE LN_ID_HISTORICO INT;
  
  SET NEW.DATA_ALTERACAO := NOW();
  
  SELECT HC.ID_HISTORICO
    INTO LN_ID_HISTORICO
    FROM HISTORICO_CONTATOS HC
    WHERE HC.ID_CONTATO = OLD.ID_CONTATO;
    
  IF OLD.NOME <> NEW.NOME  THEN
    UPDATE HISTORICO_CONTATOS
      SET NOME = NEW.NOME
         ,DATA_ALTERACAO = NEW.DATA_ALTERACAO
      WHERE ID_HISTORICO = LN_ID_HISTORICO;
  END IF;
  
  IF OLD.NUMERO_PRINCIPAL <> NEW.NUMERO_PRINCIPAL THEN
     UPDATE HISTORICO_CONTATOS
      SET NUMERO_PRINCIPAL = NEW.NUMERO_PRINCIPAL
         ,DATA_ALTERACAO = NEW.DATA_ALTERACAO
      WHERE ID_HISTORICO = LN_ID_HISTORICO;
  END IF;
  
  IF  NEW.NUMERO_SECUNDARIO <> OLD.NUMERO_SECUNDARIO THEN
     UPDATE HISTORICO_CONTATOS
      SET NUMERO_SECUNDARIO = NEW.NUMERO_SECUNDARIO
         ,DATA_ALTERACAO = NEW.DATA_ALTERACAO
      WHERE ID_HISTORICO = LN_ID_HISTORICO;
  END IF;
  
END $$;
