USE BD_AGENDA;

DELIMITER $$;
CREATE TRIGGER EXCLUIR_LOGIN_BD BEFORE 
DELETE ON LOGIN FOR EACH ROW

BEGIN
   DELETE FROM CONTATOS WHERE ID_LOGIN = OLD.ID_LOGIN;
   DELETE FROM HISTORICO_CONTATOS WHERE ID_LOGIN = OLD.ID_LOGIN;
END $$;