USE BD_AGENDA;

DELIMITER $$;
CREATE TRIGGER EXCLUIR_REG_CONTATOS_BD BEFORE
DELETE ON CONTATOS FOR EACH ROW

BEGIN
   DECLARE LN_ID_HISTORICO INT;
   
   SELECT ID_HISTORICO
    INTO LN_ID_HISTORICO
    FROM HISTORICO_CONTATOS
    WHERE ID_CONTATO = OLD.ID_CONTATO;
    
   UPDATE HISTORICO_CONTATOS
    SET STATUS_CONTATO = 'EXCLUIDO'
    WHERE ID_HISTORICO = LN_ID_HISTORICO;
    
END $$;

