USE BD_AGENDA;

DROP TRIGGER INSERIR_REG_HISTORIO_CONTATOS_AI;
DELIMITER $$;
CREATE TRIGGER INSERIR_REG_HISTORIO_CONTATOS_AI AFTER
INSERT ON CONTATOS FOR EACH ROW

BEGIN
   
  INSERT INTO HISTORICO_CONTATOS(ID_CONTATO, NOME, NUMERO_PRINCIPAL,
								 NUMERO_SECUNDARIO, ID_LOGIN) VALUES(NEW.ID_CONTATO, NEW.NOME, NEW.NUMERO_PRINCIPAL,
														  NEW.NUMERO_SECUNDARIO, NEW.ID_LOGIN);
END $$;

